###
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "username": "user3",
  "email": "user3@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/expense
Content-Type: application/json
Authorization: YOUR_TOKEN

{
  "amount": 900,
  "description": "Dinner",
  "splits": [
    {
      "user": "USER_ID_1",
      "amountOwed": 300
    },
    {
      "user": "USER_ID_2",
      "amountOwed": 300
    },
    {
      "user": "USER_ID_3",
      "amountOwed": 300
    }
  ]
}
###
GET http://localhost:3000/api/balances
Authorization: Bearer YOUR_TOKEN